/**
 * Regenerate `src/abi/lb-router.ts` and `src/abi/test-token.ts` from forge's
 * build artifacts.
 *
 *   bun run --cwd packages/sdk generate:lb-abi
 *
 * Same rule and same reason as `generate-abi.ts` next door: `contracts/out/` is
 * gitignored, so a clone has no artifact until `forge build` runs, and a
 * hand-written ABI encodes a different selector that reverts on chain with a
 * message pointing nowhere. Generating removes the class of error.
 *
 * ONLY THE FUNCTIONS THE APP CALLS ARE KEPT, and every custom error is. The
 * functions are a small, named list because an ABI is also documentation of
 * what this product is allowed to do: `addLiquidity` and four ERC20 methods.
 * The errors are kept WHOLESALE because viem decodes a revert by matching it
 * against the ABI, and an error missing from the list surfaces as an unreadable
 * hex blob at exactly the moment somebody needs to read it.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = resolve(HERE, '../../..')
const OUT_DIR = resolve(REPO, 'packages/sdk/src/abi')

interface AbiEntry {
  type: string
  name?: string
}

async function abiFrom(artifactPath: string): Promise<Array<AbiEntry>> {
  const full = resolve(REPO, artifactPath)
  let raw: string
  try {
    raw = await readFile(full, 'utf8')
  } catch {
    throw new Error(
      `No artifact at ${artifactPath}. Run \`forge build\` in contracts/ first.`,
    )
  }
  return (JSON.parse(raw) as { abi: Array<AbiEntry> }).abi
}

function keep(
  abi: Array<AbiEntry>,
  functions: ReadonlyArray<string>,
): Array<AbiEntry> {
  const fns = abi.filter(
    (e) => e.type === 'function' && functions.includes(e.name ?? ''),
  )
  const missing = functions.filter((n) => !fns.some((f) => f.name === n))
  if (missing.length > 0) {
    throw new Error(`artifact is missing: ${missing.join(', ')}`)
  }
  return [...fns, ...abi.filter((e) => e.type === 'error')]
}

async function emit(
  file: string,
  name: string,
  abi: Array<AbiEntry>,
  note: string,
) {
  const body = `/**
 * GENERATED by scripts/generate-lb-abi.ts. Do not edit by hand.
 *
${note}
 */
export const ${name} = ${JSON.stringify(abi, null, 2)} as const
`
  await writeFile(resolve(OUT_DIR, file), body, 'utf8')
  const fns = abi.filter((e) => e.type === 'function').length
  const errs = abi.filter((e) => e.type === 'error').length
  console.log(`wrote ${file}  ${fns} functions, ${errs} errors`)
}

await mkdir(OUT_DIR, { recursive: true })

await emit(
  'lb-router.ts',
  'lbRouterAbi',
  keep(await abiFrom('contracts/out/LBRouter.sol/LBRouter.json'), [
    'addLiquidity',
  ]),
  ` * Liquidity Book's router, from joe-v2 v2.2 as vendored in contracts/lib.
 * Only \`addLiquidity\` is kept: this product opens positions and does not
 * swap, and an ABI is also a statement of what the app may do.`,
)

await emit(
  'test-token.ts',
  'testTokenAbi',
  keep(await abiFrom('contracts/out/TestToken.sol/TestToken.json'), [
    'allowance',
    'approve',
    'balanceOf',
    'decimals',
    'mint',
  ]),
  ` * Our own mintable ERC20 (contracts/src/TestToken.sol). \`mint\` is open on
 * purpose and exists only on a testnet deployment; see that file for why.`,
)
