/**
 * GENERATED by scripts/generate-lb-abi.ts. Do not edit by hand.
 *
 * Liquidity Book's router, from joe-v2 v2.2 as vendored in contracts/lib.
 * Only `addLiquidity` is kept: this product opens positions and does not
 * swap, and an ABI is also a statement of what the app may do.
 */
export const lbRouterAbi = [
  {
    "type": "function",
    "name": "addLiquidity",
    "inputs": [
      {
        "name": "liquidityParameters",
        "type": "tuple",
        "internalType": "struct ILBRouter.LiquidityParameters",
        "components": [
          {
            "name": "tokenX",
            "type": "address",
            "internalType": "contract IERC20"
          },
          {
            "name": "tokenY",
            "type": "address",
            "internalType": "contract IERC20"
          },
          {
            "name": "binStep",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountX",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountY",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountXMin",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountYMin",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "activeIdDesired",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "idSlippage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deltaIds",
            "type": "int256[]",
            "internalType": "int256[]"
          },
          {
            "name": "distributionX",
            "type": "uint256[]",
            "internalType": "uint256[]"
          },
          {
            "name": "distributionY",
            "type": "uint256[]",
            "internalType": "uint256[]"
          },
          {
            "name": "to",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "refundTo",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "amountXAdded",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountYAdded",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountXLeft",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountYLeft",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "depositIds",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "liquidityMinted",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "error",
    "name": "JoeLibrary__InsufficientAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "JoeLibrary__InsufficientLiquidity",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LBRouter__AmountSlippageBPTooBig",
    "inputs": [
      {
        "name": "amountSlippage",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__AmountSlippageCaught",
    "inputs": [
      {
        "name": "amountXMin",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountX",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountYMin",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountY",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__BinReserveOverflows",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__BrokenSwapSafetyCheck",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LBRouter__DeadlineExceeded",
    "inputs": [
      {
        "name": "deadline",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "currentTimestamp",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__FailedToSendNATIVE",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__IdDesiredOverflows",
    "inputs": [
      {
        "name": "idDesired",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "idSlippage",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__IdOverflows",
    "inputs": [
      {
        "name": "id",
        "type": "int256",
        "internalType": "int256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__IdSlippageCaught",
    "inputs": [
      {
        "name": "activeIdDesired",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "idSlippage",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "activeId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__InsufficientAmountOut",
    "inputs": [
      {
        "name": "amountOutMin",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__InvalidTokenPath",
    "inputs": [
      {
        "name": "wrongToken",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__InvalidVersion",
    "inputs": [
      {
        "name": "version",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__LengthsMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LBRouter__MaxAmountInExceeded",
    "inputs": [
      {
        "name": "amountInMax",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__NotFactoryOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LBRouter__PairNotCreated",
    "inputs": [
      {
        "name": "tokenX",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenY",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "binStep",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__SenderIsNotWNATIVE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LBRouter__SwapOverflows",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__TooMuchTokensIn",
    "inputs": [
      {
        "name": "excess",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__WrongAmounts",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "reserve",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__WrongNativeLiquidityParameters",
    "inputs": [
      {
        "name": "tokenX",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenY",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amountX",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountY",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "msgValue",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LBRouter__WrongTokenOrder",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PackedUint128Math__SubUnderflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TokenHelper__TransferFailed",
    "inputs": []
  }
] as const
